# TODO

# Year ranges
operating_start_year: 2026
operating_end_year: 2050
install_start_year: 2026
install_end_year: 2035

# Units
currency_unit: "£"
energy_price_unit: "p/kWh"
heat_demand_unit: "kWh/year"

# Fuel <-> system type mapping
fuel_by_system_type:
  air_to_water_heat_pump: electricity
  gas_boiler: gas

# Discounting default
default_discount_rate: 0.035 # UK HM Treasury Green Book social discount rate
