# Global parameters used for default modelling values and assumptions.

# Year ranges to model
# Operating corresponds to years that heating systems could be operating (for which energy prices are modelled)
operating_start_year: 2026
operating_end_year: 2050
# Install corresponds to years that heating systems could be installed
install_start_year: 2026
install_end_year: 2035

# Units
currency_unit: "£"
energy_price_unit: "p/kWh"
heat_demand_unit: "kWh/year"

# Fuel <-> system type mapping
fuel_by_system_type:
  air_to_water_heat_pump: electricity
  gas_boiler: gas

# Discounting default
default_discount_rate: 0.035 # UK HM Treasury Green Book social discount rate

# Inflation rate default
default_inflation_rate: 0.02
